src/jira.js, test/.eslintrc, test/jira-tests.js
Should resolve PR to upstream project steves/node-jira#120
/cc @kernel72
=> Add request timeout option

src/jira.js, test/jira-tests.js
=> Change to use async/await

src/jira.js, test/jira-tests.js
Addresses PR from steves/node-jira#92
/cc @ghost
=> Add listStatus function

src/jira.js, test/jira-tests.js
__NOTE__: This is a small breaking change to the existing API
/cc @KanoYugoro
=> Changed makeUri to account for query string parameters

src/jira.js, test/jira-tests.js
=> Webhook api url fix

src/jira.js, test/jira-tests.js
This should fix the problem seen in issue #35
=> Fixed getLastSprintForRapidView

src/jira.js, test/jira-tests.js
Should be getting /myself instead of /session.
=> Fix getCurrentUser()

src/jira.js, test/jira-tests.js
Squashed to one commit - sorry for submitting two pull requests rebasing turned into a disaster quick.
=> squash to one commit

src/jira.js
Fixes issue #115, interpolates bool to string.
=> resolves #115

src/jira.js, test/jira-tests.js
The jira api docs call it experimental, but it seems to work fine.
=> adding createUser

src/jira.js, test/jira-tests.js
=> Intermediate path fix

src/jira.js, test/jira-tests.js
Add fieldOption APIs base on [jira docs](https://docs.atlassian.com/jira/REST/cloud/)
P/s: How often do you push new versions to npm?
=> Add field option API suite

src/jira.js, test/jira-tests.js
Hello!
I added the [`updateComment`](https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-updateComment) method implementation.
=> Add updateComment method

src/jira.js, test/jira-tests.js
This function allows you to retrieve an issues property value using the
property key.  See API here
https://docs.atlassian.com/jira/REST/cloud/#api/2/issue/{issueIdOrKey}/properties-getProperty
=> Add getIssueProperty function

src/jira.js, test/jira-tests.js
=> Issue notify

package.json, src/jira.js, test/jira-tests.js
Fixes #144 
Changes package.json to conform to updated NPM standards.
=> Find issue

src/jira.js, test/jira-tests.js
=> Adding Agile Board API

src/jira.js, test/jira-tests.js
=> Adding Agile Epic API

src/jira.js, test/jira-tests.js
=> modified signature of updateIssue to be able to write to query string

src/jira.js, test/jira-tests.js
=> Add ability to get details of single version

src/jira.js
This change is to add the ability to get the watchers of an issue by issue key
=> Add getIssueWatchers method

test/jira-tests.js
Add missing tests from https://github.com/jira-node/node-jira-client/pull/208
=> Add tests for getIssueWatchers method

src/jira.js, test/jira-tests.js
- Add missing tests from https://github.com/jira-node/node-jira-client/pull/206
- Rename `getIssueChangeLog` to `getIssueChangelog` to follow the Jira documentation
=> Add getIssueChangelog method

src/jira.js
=> Document the "bearer" token option for OAuth

src/jira.js, test/jira-tests.js
https://github.com/jira-node/node-jira-client/pull/200
=> Add getServerInfo method

test/jira-tests.js
https://github.com/jira-node/node-jira-client/pull/205
=> Add test for moveVersion

package-lock.json, src/jira.js, test/jira-tests.js
Hi Guys,
I saw there was no activity the past month in #227 so I took the code from there and added some tests to make sure it works.
Thanks,
Bart
=> Fix getAllBoards call

src/jira.js, test/jira-tests.js
Pass an SSL certificate authority through to the request-promise library.
=> Certificate Authority Option

src/jira.js, test/jira-tests.js
I implemented a new function to download an issue's attachment.
=> Add attachment download function

src/jira.js, test/jira-tests.js
Signed-off-by: Sanjeev Premi <spremi@ymail.com>
=> Add method relatedIssueCounts

src/jira.js, test/jira-tests.js
=> Adding Agile Issue API

.travis.yml, package-lock.json, package.json, src/jira.js, test/jira-tests.js, test/mocha.opts
- Remove Node 6 on Travis
- Require Node >= 10 in package.json
=> Update npm dependencies

src/jira.js, test/jira-tests.js
Was added getWorklogs function, returns details for a list of worklogs IDs
=> getWorklogs function was added

src/jira.js, test/jira-tests.js
=> Add support for listIssueLinkTypes

src/jira.js, test/jira-tests.js
I'm open to doing this in a more general way - but this seemed liked the simplest solution.
=> fix encoding for attachments. 

src/jira.js, test/jira-tests.js
A few functions regarding Comments from the API that wasn't implemented yet..
Closes #279
=> Allow getting and deleting comments

src/jira.js, test/jira-tests.js
=> Change assignee based on accountId instead of name

src/jira.js
The issueId is actually a string and not a number (called out as string elsewhere).
=> Change issueId documentation value

src/jira.js
Fix for https://github.com/jira-node/node-jira-client/issues/290
=> Document ca constructor option to address issue 290

src/jira.js
Addressing issues folks are logging because of the maxResults behavior.
e.g. https://github.com/jira-node/node-jira-client/issues/258
=> Add information about maxResults usage

src/jira.js
To address https://github.com/jira-node/node-jira-client/issues/255
=> Document API token usage on Cloud

src/jira.js, test/jira-tests.js
This is half of the https://github.com/jira-node/node-jira-client/issues/289
=> Add in /issue/createmetadata

.github/workflows/push.yml, .travis.yml, README.md
https://github.com/jira-node/node-jira-client/issues/267
Travis is currently an issue because CI is not running on PR and I don't have access to Travis settings for this repo 🙈  The permissions model of GH Actions is a much better fit ⭐
=> Use GH Actions as CI

src/jira.js
I needed a function to get sprint details like start and end dates. Also added a `genericAgileGet` function since that would have also solved my usecase but was missing as well
=> Add Get Sprint Function

package-lock.json, package.json, src/jira.js
refs: https://github.com/jira-node/node-jira-client/issues/300#issuecomment-686431243
@pioug 
I replaced `promise` with `postman-request`.
Now, `json-schema`, a dependency of `request`, has a vulnerability, and it would be nice that would be also resolved.
=> Moving to postman-request
