spec/jira.spec.coffee

They were not changed to account for the expand field defaults in a
query that was modified.

Fixed unit tests

---

src/jira.js
test/jira-tests.js

Sometimes, there is no response during a successful operation from the
JIRA rest API, and this should handle that in the short term.  A better
solution might be to check the status code of the response, and only
check for errors if it is a 4XX or 5XX status code.  This is an attempt
to resolve issue #20

Account for empty responses from rest API

---

src/jira.js
test/jira-tests.js

Allows for versions to be deleted per [JIRA version delete API](https://docs.atlassian.com/jira/REST/latest/#api/2/version-delete). Verified against local JIRA instance and unit tests pass.

Adds support for the version delete operation.

---

src/jira.js
test/jira-tests.js

This function should use the greenhopper api rather than the standard rest api (why atlassian why?)
As is this forms the url `https://[host].atlassian.net/rest/api/2/rapidviews/list` but should be `https://[host].atlassian.net/rest/greenhopper/1.0/rapidviews/list`

`findRapidView` should use the sprint uri not api uri

---

src/jira.js
test/jira-tests.js

The whole resource expansion concept of JIRA is described here: https://docs.atlassian.com/jira/REST/cloud/#expansion
I want to use this new parameter to be able to fetch the changelog of an issue.

Add parameter to specify resource expansion for findIssue

---

src/jira.js

I've added the ability to get the full list of rapid views if no specific string is provided.  Also noticed `.filter()[0]` being used, optimized by using `.find()`

Add ability to get all rapid views

---

src/jira.js
test/jira-tests.js

Added `listSprints` to return a list of sprints for a given `rapidViewId`.
Because `getLastSprintForRapidView` states it returns a list of sprints for a given rapidViewId, but does not, I felt the need to update the docs around that fn to be more appropriate.
Also created a test for `listSprints`, kind of a huge learning curve with the test framework, fwiw -- it'd be nice to understand how you've built those a bit better (docs anywhere? &hearts;)
Cheers

Created `listSprints`

---

src/jira.js
test/jira-tests.js

Commit 02319c2deb3 changed getUsersIssues in a way that makes it
generate an invalid JQL. Changing the code back to the original design
(introduced in commit f1417de), where we use the open as a boolean
variable used to decide if we constraint the JQL to return only issues
on an open status or not.

Fix wrong JQL in getUsersIssues (Issue #149)

---

src/jira.js

Added the option to supply options.bearer and use a pre-existing Bearer token in the request. This works well with atlassian-oauth2-js module here https://bitbucket.org/atlassian/atlassian-oauth2-js #168

Adding Support for Bearer Token

---

src/jira.js
test/jira-tests.js

FIXES #201
This prevents the properties get parameter from being sent through as blank in the event that there are no fields specified. According to the documentation, it should use "*all", in the same way that the fields attribute does.
https://docs.atlassian.com/jira/REST/cloud/#api/2/issue

FIX: properties key defaults to *all.

---

.travis.yml
package-lock.json

Latest of both, example here: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions . Also added package-lock.json, per npm recommendation.

Add latest stable and LTS to travis.yml tests

---

esdoc.json
package-lock.json
package.json

- Fix missing plugin from that migration https://github.com/jira-node/node-jira-client/pull/236
- Remove `esdoc-node` as it was never used in `esdoc.json`

Fix documentation build

---

src/jira.js
test/jira-tests.js

When you pass username as a string to addWatcher function,  `JSON.stringify` adds additional quotes like '"Some Username"'. Then request library escapes them and we end up with request body similar to  `body: '"\\"Some Username\\""'`, getting `The request sent by the client was syntactically incorrect` error from Jira.
Send addWatcher request using node-jira-client v.6.4.0 and Jira v. 6.4.1x 
A possible solution is just to omit `JSON.stringify` and rely on request's stringify.
This fix works for me with the latest Jira version. I've added a basic test to check the request body, but not sure if it's enough.

Send unquoted username string in addWatcher request

---

src/jira.js
test/jira-tests.js

Adding and deleting a worklog already existed, but getting a list of worklogs for a given issue was missing, which is really handy. This just adds a function to GET from the existing JIRA endpoint.

Added endpoint for list of worklogs by issueId

---

src/jira.js
test/jira-tests.js

Lets you set custom fields and set the visibility before creating the comment.
I've added it as a new function with a new name so it's not breaking.
Ideally it might be worth just swapping the current addComment function to using an object though.

Add Support for adding comments via comment object

---

src/jira.js
test/jira-tests.js

Resolves #285 by adding the ability to use the `query` parameter to search for a user as documented in Jira's API for [User Search -> Find users](https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-user-search-get).
Using the "username" parameter is deprecated (although as of this time it is still referenced in the API documentation). It will still work for some people based on their Jira privacy settings, but will eventually be enforced for everyone.
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/
> Changes to the visibility of user information: Users will be able to restrict the visibility of their personal data through their user profile privacy settings, or in the case of a managed account, the visibility …

Added "query" parameter to searchUsers

---

src/jira.js
test/jira-tests.js

Implements the feature request in issue #303

Added genericGet

---

src/jira.js
test/jira-tests.js

Hello,
I noticed that currently an API does not support the [Delete attachment](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-attachments/#api-rest-api-3-attachment-id-delete) method (which was already requested in #296 ), so here is its implementation.

Add a method for deleting attachments

---

src/jira.js

I was trying to use the `addIssueToSprint` function and kept getting 404's back from the JIRA API.  After some digging, it looks like it's now located in the agile api with a few minor changes.  I was able to successfully add an issue to a sprint this these updates.
Heres the example from the updated docs:
```
curl --request POST \
--user email@example.com:<api_token> \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '
{
"issues": [
"PR-1",
"10001",
"PR-3"
]
}' \
--url 'https://your-domain.atlassian.net/rest/agile/1.0/sprint/{sprintId}/issue'
```
https://developer.atlassian.com/cloud/jira/software/rest/
Thanks!

New sprint issue end point?!

---

package-lock.json
package.json
src/jira.js
test/jira-tests.js

Using the library, I noticed I was not getting an error in the scenario where I was using the client with a missing or incorrect token:
```
const jira = new Jira({
protocol: "https",
host: "jira.somehost.com",
username: "valid@username.com",
password: "invalid-token",
});
const res = await jira.searchJira('project = COOLPROJECT');
```
Instead of throwing an error, res is the string "Basic authentication with passwords is deprecated.  For more information, see: https://developer.atlassian.com/cloud/confluence/deprecation-notice-basic-auth/"
This PR updates the logic in the `doRequest` and `request` functions to throw an error if:
- postman-request fails with an error
- request has a status code in the 400s or 500s
I used a tool called [rewire](https://github.com/jhnns/rewire) to mock …

Throw error on failed request

---

src/jira.js
test/jira-tests.js

Currently this error is being thrown with an object (an array of error messages) - this PR changes the error parameter to a string comprised of the concatenation of the errors in the object into a comma separated string.

Fix error throw parameter on doRequest

---

src/jira.js
test/jira-tests.js

Group no longer uses its base endpoint, but appends /member - also surfaced the `includeInactiveUsers` option

Updating deprecated endpoint and surfacing inactive user option
